In [14]:
from plotly.subplots import make_subplots

import pandas as pd
import plotly.graph_objects as go

In [15]:
#1
TARGET_PATH = '../data/data.csv'
TARGET_PATH3 = '../data/data3.csv'

In [16]:
#2
df = pd.read_csv(TARGET_PATH, encoding='utf-8-sig')
df3 = pd.read_csv(TARGET_PATH3, encoding='cp949')

In [17]:
df.head()

,출발항코드(DEPARTURE_PORT_CODE),출발항명(DEPARTURE_PORT_NAME),도착항코드(DEST_PORT_CODE),도착항명(DEST_PORT_NAME),도착항국가(DEST_COUNTRY),기준일자(DATE),항만효율성(PORT_EFFICIENCY),총항해시간(TOTAL_SAILING_TIME),대기시간(WAITING_TIME),항만정시성(ON_TIME_PERFORMANCE)
0,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-05-28,23.69,644.50,0.0,7.94
1,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-11,22.01,608.54,0.0,16.20
2,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-11,16.52,749.45,0.0,1.36
3,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-30,22.37,634.28,0.0,7.44
4,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-30,16.37,654.99,0.0,1.80

In [18]:
df.columns.to_list()

['출발항코드(DEPARTURE_PORT_CODE)',
 '출발항명(DEPARTURE_PORT_NAME)',
 '도착항코드(DEST_PORT_CODE)',
 '도착항명(DEST_PORT_NAME)',
 '도착항국가(DEST_COUNTRY)',
 '기준일자(DATE)',
 '항만효율성(PORT_EFFICIENCY)',
 '총항해시간(TOTAL_SAILING_TIME)',
 '대기시간(WAITING_TIME)',
 '항만정시성(ON_TIME_PERFORMANCE)']

In [19]:
df['도착항명(DEST_PORT_NAME)'].unique()

<ArrowStringArray>
[                             '제벨알리항',                             '안트베르펜항',
                               '상하이항',                               '칭다오항',
                              '함부르크항',                                '홍콩항',
 'KOBC PORT&LOGISTICS INDICATOR (종합)',                              '로테르담항',
                              '싱가포르항',                               '램차방항',
                            '로스앤젤레스항',                                '뉴욕항',
                               '호치민항']
Length: 13, dtype: str

In [20]:
#3
region_map = {
    '상하이항': '극동아시아 지역',
    '칭다오항': '극동아시아 지역',
    '홍콩항': '극동아시아 지역',

    '싱가포르항': '동남아시아 지역',
    '램차방항': '동남아시아 지역',
    '호치민항': '동남아시아 지역',

    '로스앤젤레스항': '북미주 지역',
    '뉴욕항': '북미주 지역',

    '함부르크항': '유럽 지역',
    '로테르담항': '유럽 지역',
    '안트베르펜항': '유럽 지역',

    '제벨알리항': '중동 지역',

    'KOBC PORT&LOGISTICS INDICATOR (종합)': '종합'
}

df['지역'] = df['도착항명(DEST_PORT_NAME)'].map(region_map)

In [21]:
df['지역'].unique()

<ArrowStringArray>
['중동 지역', '유럽 지역', '극동아시아 지역', '종합', '동남아시아 지역', '북미주 지역']
Length: 6, dtype: str

In [22]:
df3['지역'].unique()

<ArrowStringArray>
['극동아시아 지역', '북미주 지역', '동남아시아 지역', '유럽 지역', '중동 지역']
Length: 5, dtype: str

In [23]:
#5
# 날짜 형식 변환
df['기준일자(DATE)'] = pd.to_datetime(df['기준일자(DATE)'])

# 연월 컬럼 만들기
df['연월'] = df['기준일자(DATE)'].dt.strftime('%Y년 %m월')

In [24]:
df.head()

,출발항코드(DEPARTURE_PORT_CODE),출발항명(DEPARTURE_PORT_NAME),도착항코드(DEST_PORT_CODE),도착항명(DEST_PORT_NAME),도착항국가(DEST_COUNTRY),기준일자(DATE),항만효율성(PORT_EFFICIENCY),총항해시간(TOTAL_SAILING_TIME),대기시간(WAITING_TIME),항만정시성(ON_TIME_PERFORMANCE),지역,연월
0,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-05-28,23.69,644.50,0.0,7.94,중동 지역,2025년 05월
1,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-11,22.01,608.54,0.0,16.20,중동 지역,2025년 06월
2,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-11,16.52,749.45,0.0,1.36,중동 지역,2025년 06월
3,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-30,22.37,634.28,0.0,7.44,중동 지역,2025년 06월
4,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-30,16.37,654.99,0.0,1.80,중동 지역,2025년 06월

In [25]:
print(df.columns.tolist())

['출발항코드(DEPARTURE_PORT_CODE)', '출발항명(DEPARTURE_PORT_NAME)', '도착항코드(DEST_PORT_CODE)', '도착항명(DEST_PORT_NAME)', '도착항국가(DEST_COUNTRY)', '기준일자(DATE)', '항만효율성(PORT_EFFICIENCY)', '총항해시간(TOTAL_SAILING_TIME)', '대기시간(WAITING_TIME)', '항만정시성(ON_TIME_PERFORMANCE)', '지역', '연월']

In [26]:
#6
regional = df.groupby(['지역','연월'])['항만효율성(PORT_EFFICIENCY)'].mean().round(2).reset_index()

# 5월 데이터 빼기
regional = regional[regional['연월'] != '2025년 05월']

In [27]:
#7
regional = regional[regional['지역'] != '종합']

In [28]:
regional['지역'].unique()

<ArrowStringArray>
['극동아시아 지역', '동남아시아 지역', '북미주 지역', '유럽 지역', '중동 지역']
Length: 5, dtype: str

In [29]:
volume_long = df3.melt(
    id_vars='지역',
    var_name='연월',
    value_name='물동량'
)

In [30]:
merged = pd.merge(
    regional,
    volume_long,
    on=['지역', '연월'],
    how='left'
)

In [31]:
merged.head()

         지역         연월  항만효율성(PORT_EFFICIENCY)     물동량
0  극동아시아 지역  2025년 06월                   17.51  662000
1  극동아시아 지역  2025년 07월                   18.37  692000
2  극동아시아 지역  2025년 08월                   16.36  668000
3  극동아시아 지역  2025년 09월                   15.44  676000
4  극동아시아 지역  2025년 10월                   16.63  664000

In [32]:
# 종합...

fig = make_subplots(
    specs=[[{'secondary_y': True}]]
)

# 1. 지역별 물동량 → 누적 막대
for region in merged['지역'].unique():

    temp = merged[merged['지역'] == region]

    fig.add_trace(
        go.Bar(
            x=temp['연월'],
            y=temp['물동량'],
            name=f'{region} 물동량',
            legendgroup=region
        ),
        secondary_y=False
    )


# 2. 지역별 항만효율성 → 선
for region in merged['지역'].unique():

    temp = merged[merged['지역'] == region]

    fig.add_trace(
        go.Scatter(
            x=temp['연월'],
            y=temp['항만효율성(PORT_EFFICIENCY)'],
            mode='lines+markers',
            name=f'{region} 효율성',
            legendgroup=region
        ),
        secondary_y=True
    )


# 막대 누적
fig.update_layout(
    barmode='group',
    width=1100,
    height=600
)

# 왼쪽 y축
fig.update_yaxes(
    title_text='물동량',
    secondary_y=False
)

# 오른쪽 y축
fig.update_yaxes(
    title_text='항만효율성',
    secondary_y=True
)

fig.update_xaxes(
    title_text='연월'
)

fig.show()

In [33]:
def region_graph(region):

    # 선택한 지역만 가져오기
    temp = merged[merged['지역'] == region]

    fig = make_subplots(
        specs=[[{'secondary_y': True}]]
    )

    # 물동량 막대그래프
    fig.add_trace(
        go.Bar(
            x=temp['연월'],
            y=temp['물동량'],
            name='물동량'
        ),
        secondary_y=False
    )

    # 항만효율성 선그래프
    fig.add_trace(
        go.Scatter(
            x=temp['연월'],
            y=temp['항만효율성(PORT_EFFICIENCY)'],
            mode='lines+markers',
            name='항만효율성'
        ),
        secondary_y=True
    )

    fig.update_layout(
        width=1100,
        height=600
    )

    fig.update_yaxes(
        title_text='물동량',
        secondary_y=False
    )

    fig.update_yaxes(
        title_text='항만효율성',
        secondary_y=True
    )

    fig.update_xaxes(
        title_text='연월'
    )

    return fig